# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Camporez
tagline:	'blog'
description:	'Um blog pessoal.'
url:		http://camporez.com

author:
  name:	'Ian Camporez Brunelli'
  url:	https://google.com/+IanCamporezBrunelli

paginate:	5

# Custom vars
icon: /assets/images/icon.png
cover: /assets/images/cover.jpg
version:	1.0.0
github:
  repo:	https://github.com/camporez/camporez.github.io
