# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Camporez
tagline:	'blog'
description:	'Um blog pessoal.'
url:		http://camporez.com

author:
  name:	'Ian Camporez Brunelli'
  url:	https://google.com/+IanCamporezBrunelli

paginate:	2

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/iancamporez
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/camporez
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://google.com/+IanCamporezBrunelli
    desc:	Add me on google+

  - icon:	feed
    url:	http://camporez.com/atom.xml
    desc:	Subscribe to my feed
    
menu:
  - title:	Home
    url:	http://camporez.com
    
  - title:	About
    url:	http://camporez.com/about

copyright:	<p class="copyright">&copy;2014, <a href="http://camporez.com" target="_blank">Camporez</a>. <a href="http://creativecommons.org/licenses/by-nc/2.5/br/" target="_blank">Alguns direitos reservados</a>.</p>
