# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Camporez
tagline:	'blog'
description:	'Um blog pessoal.'
url:		http://camporez.com

author:
  name:	'Ian Camporez Brunelli'
  url:	https://google.com/+IanCamporezBrunelli

paginate:	2

# Custom vars
icon: /assets/images/icon.png
cover: /assets/images/cover.jpg
version:	1.0.0
github:
  repo:	https://github.com/camporez/camporez.github.io
copyright: <p class="copyright">&copy;2014, <a href="http://camporez.com" target="_blank">Camporez</a>. <a href="http://creativecommons.org/licenses/by-nc/2.5/br/" target="_blank">Alguns direitos reservados</a>.</p>
